### ISSUE TITLE
Could not find com.commit451:PhotoViewsquareup.picasso:picasso

### ISSUE THREAD

**Issue by akhil-ksolves** [sarriaroman/photoviewer#231]
Here is my ProdPhotoViewer.gradle

repositories{
  jcenter()
}

dependencies {
   implementation 'com.commit451:PhotoView:1.2.4'
   implementation 'com.commit451:PhotoViewsquareup.picasso:picasso:2.71828'
}

android {

}

Already I using the implementation instead of compile but can not get the dependencies
 Here is the error:
 
 Could not find com.commit451:PhotoViewsquareup.picasso:picasso.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/commit451/PhotoViewsquareup.picasso/picasso/PhotoViewsquareup.picasso-picasso.pom
       - https://repo.maven.apache.org/maven2/com/commit451/PhotoViewsquareup.picasso/picasso/PhotoViewsquareup.picasso-picasso.pom
       - https://jcenter.bintray.com/com/commit451/PhotoViewsquareup.picasso/picasso/PhotoViewsquareup.picasso-picasso.pom
       
       
       Let me know if there any repository that I can add here to get the dependency

**Comment by rolinger** [comment]
@akhil-ksolves - I just resolved an issues for `cordova-plugin-qrscanner-11` by simply changing `compile` to `implementation` in the `/src/android/plugin-qrscanner.gradle` file.  I was just getting ready to do the same with this plugin when I saw your issue.  So even fixing the gradle syntax is not enough.

NPM shows the latest version for this plugin @1.2.5, yet when grabbing the ` com-sarriaroman-photoviewer@1.2.5` or even ` com-sarriaroman-photoviewer@latest` - it installs the 1.2.4 version.

Another issue https://github.com/sarriaroman/photoviewer/issues/228 references a fork for v1.3.0 but I haven't been able to find it and am not certain how to load it.  Apparently some of these issues are fixed in the fork 1.3.0

**Comment by rolinger** [comment]
@akhil-ksolves - well, I just installed version 1.2.4 again, edited the `src/android/photoviewer.gradle` file in both the base plugin as well as the `/platforms/android/com-sarriaroman-photoviewer/myApp-photoviewer.gradle` files.  I changed the `compile` to `implementation` in both files and everything installed/compiled cleanly for me.

Not certain where you are getting your `photoviewer` plugin from, but your dependencies are slightly different than whats in this plugin.   **Your picasso is different.**  Maybe you can grab this specific `com-sarriaroman-photoviewer` plugin and then edit the gradle as necessary, you shouldn't have to change the dependencies themselves, just the gradle call.

Mine:
```
dependencies {
   implementation 'com.commit451:PhotoView:1.2.4'
   implementation 'com.squareup.picasso:picasso:2.71828'
}

```

**Comment by sarriaroman** [comment]
Solved. Check https://www.npmjs.com/package/com-sarriaroman-photoviewer
